### PR TITLE
Feature: Add Dutch language

### PR DESCRIPTION
**Pull request by ceesvanegmond**
Added the Dutch language :-)

### CODE REVIEW

**Comment by arnoson** [comment]
Awesome, thank you! I just realised that I scattered the translations throughout the blueprints, should probably move them to the translation file some day

**Comment by ceesvanegmond** [comment]
@arnoson Haha! You should :-) Maybe i'll send an PR soon :-)

Could you tag this version? Maybe as `v0.4.0` or `v0.3.2`? Thanks!

**Comment by arnoson** [comment]
I'll move the translations into the languages files and then release it :)
I was thinking about renaming `Identifier` to `Name` since the word doesn't translate well to german and is a bit long. What would this be in danish, `Navn`?

**Comment by arnoson** [comment]
Released in `v0.3.2`! I hope I didn't make an error refactoring the translation, can you check again?

**Comment by ceesvanegmond** [comment]
@arnoson It would be 'Naam' indeed. Looks good! Works!

**Pull request merged**
